# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssh-connect" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "01cbc25e36dcd8f05d0f248f858279f7feaba4be278ba6a749f2c3abdc0bf7f0"
      url "https://github.com/Ragin-LundF/ssh-connect/releases/download/v#{version}/ssh_connect_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e8ab769deea7328b0b2307bc7f073e109c36cde98742130e2a927bd0b736ce22"
      url "https://github.com/Ragin-LundF/ssh-connect/releases/download/v#{version}/ssh_connect_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "eb0f8dc79e9182e12fdf0e19841d772034d8cb4ed1cee4ef4ab8068f1e00be59"
      url "https://github.com/Ragin-LundF/ssh-connect/releases/download/v#{version}/ssh_connect_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ssh-connect"
  desc "Terminal UI for organizing and connecting to SSH servers"
  homepage "https://github.com/Ragin-LundF/ssh-connect"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh_connect"

  # No zap stanza required

end
