# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshConnect < Formula
  desc "Terminal UI for organizing and connecting to SSH servers"
  homepage "https://github.com/Ragin-LundF/ssh-connect"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Ragin-LundF/ssh-connect/releases/download/v0.1.0/ssh_connect_0.1.0_macOS_arm64.tar.gz"
      sha256 "e1272ccb13bfee20ab6325aaea6c5a831d171ebb76a9a472b93516d7ff03cb00"

      define_method(:install) do
        bin.install "ssh_connect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ragin-LundF/ssh-connect/releases/download/v0.1.0/ssh_connect_0.1.0_linux_x86_64.tar.gz"
      sha256 "b5b8edeac441bc7f604e3e826705eb096ef4d37cc96f8a630933ad37a9286939"
      define_method(:install) do
        bin.install "ssh_connect"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ragin-LundF/ssh-connect/releases/download/v0.1.0/ssh_connect_0.1.0_linux_arm64.tar.gz"
      sha256 "b18ad63515f67caa599a3ac2e548d088c29b310d01625fb2c3d02150212938f7"
      define_method(:install) do
        bin.install "ssh_connect"
      end
    end
  end

  test do
    system "#{bin}/ssh_connect", "--help"
  end
end
